### PR TITLE
Add missing content = "c" for ColWidth

### PR DESCRIPTION
**Pull request by xuhongxu96**
Before fixing, it would panick at `json is not in the pandoc format: Error("invalid type: map, expected f64", line: 277, column: 5)` when there is `ColWidth` in `Table`.

### CODE REVIEW

**Comment by xuhongxu96** [comment]
Json for repro

```json
{
  "blocks": [
    {
      "c": [
        [
          "",
          [],
          []
        ],
        [
          null,
          [
            {
              "c": [
                {
                  "c": "abc",
                  "t": "Str"
                },
                {
                  "t": "Space"
                },
                {
                  "c": "def",
                  "t": "Str"
                },
                {
                  "t": "Space"
                },
                {
                  "c": "{#tbl:abc}",
                  "t": "Str"
                }
              ],
              "t": "Plain"
            }
          ]
        ],
        [
          [
            {
              "t": "AlignLeft"
            },
            {
              "c": 0.1388888888888889,
              "t": "ColWidth"
            }
          ],
          [
            {
              "t": "AlignLeft"
            },
            {
              "c": 0.4305555555555556,
              "t": "ColWidth"
            }
          ],
          [
            {
              "t": "AlignLeft"
            },
            {
              "c": 0.4305555555555556,
              "t": "ColWidth"
            }
          ]
        ],
        [
          [
            "",
            [],
            []
          ],
          [
            [
              [
                "",
                [],
                []
              ],
              [
                [
                  [
                    "",
                    [],
                    []
                  ],
                  {
                    "t": "AlignDefault"
                  },
                  1,
                  1,
                  [
                    {
                      "c": [
                        {
                          "c": "abc",
                          "t": "Str"
                        }
                      ],
                      "t": "Plain"
                    }
                  ]
                ],
                [
                  [
                    "",
                    [],
                    []
                  ],
                  {
                    "t": "AlignDefault"
                  },
                  1,
                  1,
                  [
                    {
                      "c": [
                        {
                          "c": "def",
                          "t": "Str"
                        }
                      ],
                      "t": "Plain"
                    }
                  ]
                ],
                [
                  [
                    "",
                    [],
                    []
                  ],
                  {
                    "t": "AlignDefault"
                  },
                  1,
                  1,
                  [
                    {
                      "c": [
                        {
                          "c": "ghi",
                          "t": "Str"
                        },
                        {
                          "t": "Space"
                        },
                        {
                          "c": "jkl",
                          "t": "Str"
                        }
                      ],
                      "t": "Plain"
                    }
                  ]
                ]
              ]
            ]
          ]
        ],
        [
          [
            [
              "",
              [],
              []
            ],
            0,
            [],
            [
              [
                [
                  "",
                  [],
                  []
                ],
                [
                  [
                    [
                      "",
                      [],
                      []
                    ],
                    {
                      "t": "AlignDefault"
                    },
                    1,
                    1,
                    [
                      {
                        "c": [
                          {
                            "c": "mno",
                            "t": "Str"
                          }
                        ],
                        "t": "Plain"
                      }
                    ]
                  ],
                  [
                    [
                      "",
                      [],
                      []
                    ],
                    {
                      "t": "AlignDefault"
                    },
                    1,
                    1,
                    [
                      {
                        "c": [
                          {
                            "c": "pqr",
                            "t": "Str"
                          },
                          {
                            "c": [
                              [
                                "",
                                [],
                                []
                              ],
                              "FORCE"
                            ],
                            "t": "Code"
                          },
                          {
                            "c": "stu",
                            "t": "Str"
                          }
                        ],
                        "t": "Plain"
                      }
                    ]
                  ],
                  [
                    [
                      "",
                      [],
                      []
                    ],
                    {
                      "t": "AlignDefault"
                    },
                    1,
                    1,
                    [
                      {
                        "c": [
                          {
                            "c": "vwx",
                            "t": "Str"
                          }
                        ],
                        "t": "Plain"
                      }
                    ]
                  ]
                ]
              ]
            ]
          ]
        ],
        [
          [
            "",
            [],
            []
          ],
          []
        ]
      ],
      "t": "Table"
    }
  ],
  "meta": {},
  "pandoc-api-version": [
    1,
    22,
    1
  ]
}
```

**Comment by oli-obk** [comment]
cool thanks!

**Comment by xuhongxu96** [comment]
Hi @oli-obk, seems the CI was not run. Is it possible to trigger it so that I can consume the latest version thru cargo? Thanks!

**Comment by oli-obk** [comment]
I already published a new version. sadly CI here does not actually do deployment ^^

**Pull request merged**
