### PR TITLE
Derive Clone and Copy where possible

### PR DESCRIPTION
**Pull request by Rufflewind**
Would be really convenient to have this!

(Could also add `Eq` if you’d like.)

### CODE REVIEW

**Comment by oli-obk** [comment]
I'm fine with adding more convenience derives.

Hash and Eq are a useful further addition

**Comment by Rufflewind** [comment]
Updated.  (Apparently quite a few aren’t eligible because `f64` is not `Eq+Hash`.)

**Comment by oli-obk** [comment]
Thanks!

**Comment by oli-obk** [comment]
Published as 0.7.1

**Pull request merged**
